### ISSUE TITLE
Missing jcmd binary

### ISSUE THREAD

**Issue by scbarrett** [barbolani/openSuse-install-Oracle-JDK#1]
@barbolani nice script. Of course, I found an error:
--slave /usr/share/man/man1/jcmd.1.gz jcmd.1.gz ${LIB_FOLDER}/jdk_Oracle/man/man1/jcmd.1.gz \

Needs to be proceeded by a corresponding definition of jcmd:
--slave /usr/bin/jcmd jcmd ${LIB_FOLDER}/jdk_Oracle/bin/jcmd \

**Comment by barbolani** [comment]
Hey Steve, thanks for pointing out the error. I'm off Java most of the time nowadays, so I haven't used the script in a while. Could you create a patch for fixing it? I'd gladly take it into the script.

**Comment by scbarrett** [comment]
Alfonso, you mean there's something besides Java  :-)

I ended up with a nice script that successfully took me to 1.8.0_60, and
learned a few things in the process. I'll give a patch a shot when I have a
chance . I found a couple of other things (like apt not being in version
8), which I'll add.

--Steve

**Comment by scbarrett** [comment]
Here's my patch Alfonso. It's the actual script I used, so it's been tested
on SUSE 13.2 with Java 8. The comments have been updated to reflect the
changes. Here's the branch commit message:

Fixed errors & updated for installing JDK 8_60 on SUSE 13.2.

In keeping with the spirit of SUSE, removed sudo; run as root.

Replaced variable ORACLE_JAVA (/usr/java), which 13.2 seems not to use, with JVM_FOLDER (/usr/lib(64)/jvm). This makes the main link between these two superfluous, so it's gone.

Added alternative update for JDK API documentation, javadocdir.

On Sun, Sep 6, 2015 at 12:32 PM, Stephen C. Barrett <scbarrett@santoslab.org

> wrote:
> 
> Alfonso, you mean there's something besides Java  :-)
> 
> I ended up with a nice script that successfully took me to 1.8.0_60, and
> learned a few things in the process. I'll give a patch a shot when I have a
> chance . I found a couple of other things (like apt not being in version
> 8), which I'll add.
> 
> --Steve
> 
> On Sun, Sep 6, 2015 at 11:21 AM, Alfonso García-Patiño Barbolani <

**Comment by BaygonV** [comment]
@scbarrett : i am new to github and very interested in your patch so i have a simple question : when you say "Here's my patch" where exactly is here ?

@barbolani & @scbarrett : thank you !

**Comment by barbolani** [comment]
Steve, I can't find anywhere your patch. The simplest way would be for you to branch, make whatever changes and then issue a pull request -do you need help with that?

**Comment by scbarrett** [comment]
Alfonso, I sent the patch in the e-mail that posted my previous comment. I guess GitHub doesn't pull attachments along. You asked for a "patch", so I made a patch... I will now create a branch with my code as is, and make a pull request for you to merge in.

@BaygonV, you can't find it, because I goofed. We should get it fixed soon.

**Comment by barbolani** [comment]
Steve, already merged. Thanks for the contribution.
